export default {
    LIST_ALL_PARTICIPANTS: "LIST_ALL_PARTICIPANTS",
    GET_USER_INFO: "GET_USER_INFO",
    LIST_ALL_MESSAGES: "LIST_ALL_MESSAGES",
    LIST_ALL_ADD_FRIEND_REQUEST_RECEIVED: "LIST_ALL_ADD_FRIEND_RECEIVED",
}